### ISSUE TITLE
Singletons

### ISSUE THREAD

**Issue by rcgary** [burczyk/XcodeSwiftSnippets#7]
I think the snippet for create Singleton need to be update.
What do you think?

https://thatthinginswift.com/singletons/

**Comment by burczyk** [comment]
Current solution still works, it's just a different approach. I don't think we should remove it, but feel free to make a pull request with new one. Name it like `Singleton2.swift` and provide proper description so that anyone can use snippet he better understands :)

Update: Or as I see here https://github.com/hpique/SwiftSingleton we can just use `static let` construct. It makes more sense. Will add it and keep old one for older Swift versions.

**Comment by burczyk** [comment]
Done.
